#!/bin/bash

 
NORMAL="color:#000000;"
STOPB="rgba(238,155,0,0)"
STOPF="rgba(238,155,0,0)"
STOPL="rgb(0,0,0)"
HS="9pt"
HF=""
devname="/dev/sda7"
ICONPATH="$HOME/.kde4/share/apps/be.shell/Scripts/"




if [ $1 = "sensors" ]; then

  g=`ps aux|awk 'NR > 0 { s +=$3 }; END {print "cpu %",s}'| awk '{print $3}'`
  g="${g%%.*}"
  l=`df -k $devname| grep -v ^File | awk '{ print $5 }'`
  CPU=`sensors | sed -n '/temp1/p' | awk '{ print $2 }'`
  TOT=`cat /proc/meminfo | grep MemTotal: | awk '{print $2}'`
  USED=`cat /proc/meminfo | grep Active: | awk '{print $2}'`
  let "USEDPERC=(1000*$USED/$TOT+5)"
  PERC=`echo $USEDPERC|awk '{ print $1/10 }'`
  PERC="${PERC%%.*}"
  REPLY="${REPLY}<div>$(echo "<img src=\"${ICONPATH}Memory.png\" width=\"16\" height=\"16\"> <font color=\"$NORMAL\"> $(echo $PERC)%</font>")&nbsp; $(echo "<img src=\"${ICONPATH}Gear.png\" width=\"16\" height=\"16\"> <font color=\"$NORMAL\">$g%</font>")</div>"
  echo "$REPLY"

elif [ $1 = "net" ]; then

  NET=`nmcli -t -f state g`
  
    if [ $NET = "collegato" ]; then
      echo "<img src=\"$HOME/.kde4/share/icons/flat/network-connect.svg\" width=\"20\" height=\"20\">"
    else
      echo "<img src=\"$HOME/.kde4/share/icons/flat/network-disconnect.svg\" width=\"20\" height=\"20\">"
    fi

elif [ $1 = "mpc" ]; then

  SEP="- "
  SEP1="."
  MPC=`mpc -f "[%artist%]"|head -n 1`
  MPC1=`mpc -f "[%title% ]"|head -n 1`
  MPC2=`mpc -f "[%album%]"|head -n 1`
  MPC3=`mpc -f "[%track%]"|head -n 1`
  PERC=`mpc|head -n 2|tail -n 1|awk '{ print $4 }'|sed 's/[^0-9]*//g'|awk '{print $1/100}'`
  STS=`mpc status|head -n 2|tail -n 1|awk '{ print $1 }'`
  
    if [ $STS = "[playing]" ]; then
    
      BG="background-color: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 ${STOPB}, stop: $(echo $PERC - 0.025|bc) ${STOPB},stop: ${PERC} ${STOPL}, stop: $(echo $PERC + 0.025|bc) ${STOPF},  stop: 1 ${STOPF});"
      DIVHEADER="<table valign="middle" cellspacing="0" cellpadding="0" style=\"${BG}\"><tr>"
      echo "$DIVSTYLE$DIVHEADER<td><b>$MPC</b>$MPC1</td><td>$SEP</td><td><b>$MPC2</b></td><td>$SEP1</td><td>$MPC3</td></tr></table>"
  
    elif [ $STS = "[paused]" ]; then
  
      BG="background-color: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 ${STOPB}, stop: $(echo $PERC - 0.025|bc) ${STOPB},stop: ${PERC} ${STOPL}, stop: $(echo $PERC + 0.025|bc) ${STOPF},  stop: 1 ${STOPF});"
      DIVHEADER="<table valign="middle" cellspacing="0" cellpadding="0" style=\"${BG}\"><tr>"
      echo "$DIVSTYLE$DIVHEADER<td><b>paused </b></td><td>$SEP</td><td><b>$MPC2</b></td><td>$SEP1</td><td>$MPC3</td></tr></table>"
  
    else
  
      BG="background-color:transparent"
      DIVHEADER="<table valign="middle" cellspacing="0" cellpadding="0" style=\"${BG}\"><tr>"
      echo "$DIVSTYLE$DIVHEADER<td><b>mpd</b>stop</td></tr></table>"
  
    fi
  
elif [ $1 = "mail" ]; then

  username=
  password=

  url="https://mail.google.com/mail/feed/atom"
  COUNT=$(curl --silent --url "$url" --user $username:$password | sed -r 's/.*<fullcount>|<\/fullcount>.*//g')
  echo $COUNT
  
elif [ $1 = "update" ]; then

  UPR=`checkupdates | wc -l`
  TOTR=`pacman -Qn | wc -l`
  AUR=`cower -u | wc -l`
  TOTA=`pacman -Qm | wc -l`
  
  BG="background-color: transparent"
  DIVHEADER="<table valign="middle" cellspacing="0" cellpadding="0" style=\"${BG}\"><tr>"
  echo "$DIVSTYLE$DIVHEADER<td><b>$UPR</b></td><td>$TOTR</td><td><b>$AUR</b></td><td>$TOTA</td></tr></table>"
  
fi  
