#!/bin/bash

NORMAL="color:#000000;"
STOPB="rgba(238,155,0,0)"
STOPF="rgba(238,155,0,0)"
STOPL="rgb(0,0,0)"
HS="9pt"
HF=""

if [ $1 = "net" ]; then

  NET=`nmcli -t -f state g`
  
    if [ $NET = "collegato" ]; then
      echo "<img src=\"$HOME/.kde4/share/icons/flat/nm-connect.png\">"
    else
      echo "<img src=\"$HOME/.kde4/share/icons/flat/nm-signal-0.png\" >"
    fi
    
elif [ $1 = "wifi" ]; then

  NET=`iwlist scan 2>/dev/null | sed -e '/Quality/!d; s/.*Quality=\([0-9]*\).*/\1/'`
  
    if [ $NET > 61 ]; then
      echo "<img src=\"$HOME/.kde4/share/icons/flat/nm-signal-100.png\" >"
    elif [ $NET > 44 ]; then
      echo "<img src=\"$HOME/.kde4/share/icons/flat/nm-signal-75.png\" >"
    elif [ $NET > 26 ]; then
      echo "<img src=\"$HOME/.kde4/share/icons/flat/nm-signal-50.png\" >"
    elif [ $NET > 9 ]; then
      echo "<img src=\"$HOME/.kde4/share/icons/flat/nm-signal-25.png\" >"
    else
      echo "<img src=\"$HOME/.kde4/share/icons/flat/nm-signal-0.png\" >"
    fi

elif [ $1 = "mpc" ]; then

  SEP=" "
  SEP1="-"
  MPC=`mpc -f "[%artist%]"|head -n 1`
  MPC1=`mpc -f "[%title% ]"|head -n 1`
  MPC2=`mpc -f "[%album%]"|head -n 1`
  MPC3=`mpc -f "[%track%]"|head -n 1`
  PERC=`mpc|head -n 2|tail -n 1|awk '{ print $4 }'|sed 's/[^0-9]*//g'|awk '{print $1/100}'`
  STS=`mpc status|head -n 2|tail -n 1|awk '{ print $1 }'`
  
    if [ $STS = "[playing]" ]; then
    
      #BG="background-color: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 ${STOPB}, stop: $(echo $PERC - 0.025|bc) ${STOPB},stop: ${PERC} ${STOPL}, stop: $(echo $PERC + 0.025|bc) ${STOPF},  stop: 1 ${STOPF});"
      BG="background-color:transparent"
      DIVHEADER="<table valign="middle" cellspacing="0" cellpadding="0" style=\"${BG}\"><tr>"
      echo "$DIVSTYLE$DIVHEADER<td><img src=\"$HOME/.kde4/share/icons/Yosemite-color/mine/play_t.svg\"width=\"16\"></td><td>$SEP</td><td>$SEP</td><td>$SEP</td><td>$SEP</td><td><b>$MPC</b></td><td>$SEP</td><td>$SEP1</td><td>$SEP</td><td>$MPC1</td><td>$SEP</td><td><b>$MPC2</b></td><td>$SEP</td><td>$SEP1</td><td>$SEP</td><td>$MPC3</td></tr></table>"
  
    elif [ $STS = "[paused]" ]; then
  
      #BG="background-color: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 ${STOPB}, stop: $(echo $PERC - 0.025|bc) ${STOPB},stop: ${PERC} ${STOPL}, stop: $(echo $PERC + 0.025|bc) ${STOPF},  stop: 1 ${STOPF});"
      BG="background-color:transparent"
      DIVHEADER="<table valign="middle" cellspacing="0" cellpadding="0" style=\"${BG}\"><tr>"
      echo "$DIVSTYLE$DIVHEADER<td><img src=\"$HOME/.kde4/share/icons/Yosemite-color/mine/pause_t.svg\"width=\"16\"></td><td>$SEP</td><td>$SEP</td><td>$SEP</td><td>$SEP</td><td><b>$MPC2</b></td><td>$SEP</td><td>$SEP1</td><td>$SEP</td><td>$MPC3</td></tr></table>"
  
    else
  
      BG="background-color:transparent"
      DIVHEADER="<table valign="middle" cellspacing="0" cellpadding="0" style=\"${BG}\"><tr>"
      echo "$DIVSTYLE$DIVHEADER<td><img src=\"$HOME/.kde4/share/icons/Yosemite-color/mine/stop_t.svg\"width=\"14\"></td></tr></table>"
  
    fi
  
elif [ $1 = "mail" ]; then

  username=
  password=
  url="https://mail.google.com/mail/feed/atom"
  COUNT=$(curl --silent --url "$url" --user $username:$password | sed -r 's/.*<fullcount>|<\/fullcount>.*//g')
  
  if [ $COUNT == 0 ]; then
    BG="background-color: transparent"
    DIVHEADER="<table valign="middle" cellspacing="0" cellpadding="0" style=\"${BG}\"><tr>"
    echo "$DIVSTYLE$DIVHEADER<td><img src=\"$HOME/.kde4/share/icons/Yosemite-color/mine/nomail.svg\"width=\"16\"></td></tr></table>"
  else
    BG="background-color: transparent"
    DIVHEADER="<table valign="middle" cellspacing="0" cellpadding="0" style=\"${BG}\"><tr>"
    echo "$DIVSTYLE$DIVHEADER<td><img src=\"$HOME/.kde4/share/icons/Yosemite-color/mine/mail.svg\"width=\"16\"></td></tr></table>"
  fi
  
elif [ $1 = "up" ]; then

  UPR=`checkupdates | wc -l`
  
    if [ $UPR == 0 ]; then
      BG="background-color: transparent"
      DIVHEADER="<table valign="middle" cellspacing="0" cellpadding="0" style=\"${BG}\"><tr>"
      echo "$DIVSTYLE$DIVHEADER<td><img src=\"$HOME/.kde4/share/icons/Yosemite-color/mine/noupdate.svg\"width=\"16\"></td></tr></table>"
    else
      BG="background-color: transparent"
      DIVHEADER="<table valign="middle" cellspacing="0" cellpadding="0" style=\"${BG}\"><tr>"
      echo "$DIVSTYLE$DIVHEADER<td><img src=\"$HOME/.kde4/share/icons/Yosemite-color/mine/update.svg\"width=\"16\"></td></tr></table>"
    fi
  
fi  
